sonar.projectKey=NaoseiBTT_vendeai
sonar.organization=naoseibtt
sonar.sources=backend

sonar.sources=backend/src

# Caminho para o relatório de cobertura gerado pelo Jest
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

# Exclui arquivos de teste da análise de cobertura
sonar.exclusions=backend/src/**/*.spec.ts, backend/src/**/*.test.ts